#!/bin/bash

# Questão numero 2 data 31 12 2002

#cal -31 12 2002 >> file.txt
#awk '{print$3}' file.txt | head -2

# Questao numero 3 

#cal 2005 >> /home/demo/yearfile
 
# Questao numero 4

#ls -a /home/demo | wc -l

# Questão numero 5 file size 

#ls -al /home/demo | grep '^-' | awk '{print$5}'| sort -rn | tail -1

# Questáo numero 6 funciona - mas tem que coincidir com o horario do linuxzoo
#cal -1 >> /home/raven/thismonth && date >> /home/raven/thismonth

# Questão numero 7 

#echo >> /home/demo/yearfile
#cp /home/demo/yearfile /home/demo/yearfile2
#cp /home/demo/yearfile /home/demo/yearfile3

# Questão numero 8 moving 

#mv /home/demo/yearfile3 /home/demo/thisyear

# Questao numero 9 Deleting 

#rm -r yearfile

# Questão numero 10 concat

#cat thismonth yearfile2 thisyear > bigfile 
